# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-16:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer
    - name: Show available destinations
      run: xcodebuild -scheme Engine -showdestinations
    - name: Build for macOS
      run: xcodebuild -scheme Engine -destination 'platform=macOS' build
    - name: Build for Catalyst
      run: xcodebuild -scheme Engine -destination 'platform=macOS,variant=Mac Catalyst' build
    - name: Build for iOS
      run: xcodebuild -scheme Engine -destination 'platform=iOS Simulator,name=iPhone 16' build
    - name: Build for watchOS
      run: xcodebuild -scheme Engine -destination 'platform=watchOS Simulator,name=Apple Watch Ultra 2 (49mm)' build
    - name: Build for tvOS
      run: xcodebuild -scheme Engine -destination 'platform=tvOS Simulator,name=Apple TV 4K (3rd generation)' build
  build-26:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_26.0.app/Contents/Developer
    - name: Show available destinations
      run: xcodebuild -scheme Engine -showdestinations
    - name: Build for macOS
      run: xcodebuild -scheme Engine -destination 'platform=macOS' build
    - name: Build for Catalyst
      run: xcodebuild -scheme Engine -destination 'platform=macOS,variant=Mac Catalyst' build
    - name: Build for iOS
      run: xcodebuild -scheme Engine -destination 'platform=iOS Simulator,name=iPhone 17' build
    - name: Build for watchOS
      run: xcodebuild -scheme Engine -destination 'platform=watchOS Simulator,name=Apple Watch Ultra 3 (49mm)' build
    - name: Build for tvOS
      run: xcodebuild -scheme Engine -destination 'platform=tvOS Simulator,name=Apple TV 4K (3rd generation)' build
